
import { Geist, Geist_Mono, Pacifico } from "next/font/google";
import "./globals.css";
import Image from "next/image";

const pacifico = Pacifico({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-pacifico',
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Unicorn Digital",
  description: "Generated by Readdy",
  icons: [
    { rel: "icon", url: "/favicon.ico", type: "image/x-icon" },
  ]
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <head>
        <link href="https://cdn.jsdelivr.net/npm/remixicon@4.0.0/fonts/remixicon.css" rel="stylesheet" />
        <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
       
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${pacifico.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
